### ISSUE TITLE
[CI] Add CPU-only CI job(s)

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/ucxx#231]
## Description

This project should add one or more CI jobs running some subset of the tests in an environment without a GPU.

## Benefits of this work

Improves release confidence by reducing the risk of merging changes that break CPU-only support.

## Approach

This could be accomplished by using the `custom-job` shared action from `shared-workflows` ([code link](https://github.com/rapidsai/shared-workflows/blob/19d17957e59cf81574f214e043adf8cff7db9447/.github/workflows/custom-job.yaml#L18)) and targeting a CPU node, like this:

```yaml
  cpu-only-tests:
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
        node_type: cpu4
        build_type: pull-request
        run_script: "ci/run-cpu-tests.sh"
```

For an example, see how `cudf` runs the `pandas` unit tests on a CPU-only runner:

https://github.com/rapidsai/cudf/blob/516d0f9033e73d10a473e2ca3fcc891e980450bc/.github/workflows/pr.yaml#L182-L189

## Notes

This issue is inspired by a recent experience over on `ucx-py`. There, while testing https://github.com/rapidsai/ucx-py/pull/1041, a CPU-only job (in that example, docs building) caught that some changes would have made that library unusable without access to a GPU.

For more details, see https://github.com/rapidsai/ucx-py/pull/1041#discussion_r1594729142.
